services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container_reservation_ms
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_reservation_ms
      MYSQL_USER: localhost
      MYSQL_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - mysql_data_reservation_ms:/var/lib/mysql

volumes:
  mysql_data_reservation_ms:
